"use client";

import { motion } from "motion/react";
import { useEffect, useRef, useState } from "react";

/**
 * The opening doors behind the intro.
 *
 * The clip runs 5.0s and the full intro runs 5.05s, so the doors part across
 * the whole sequence rather than being cut off part-way: the dust gathers while
 * they open, and the warm room is at its widest as the overlay lifts into the
 * hero.
 *
 * They do not disappear when the mark arrives. They recede — down to a low
 * opacity behind a navy scrim — so the gold monogram reads cleanly with the
 * room still glowing behind it. Cutting them entirely threw away the best
 * moment of the clip a beat before it happened.
 *
 * The clip is decorative and silent by design: the audio track is stripped at
 * encode time, and it is muted and `playsInline` so mobile browsers will
 * actually autoplay it. Anything that stops it from playing — a missing file, a
 * decode error, a refused autoplay, Data Saver — drops the layer entirely and
 * the intro plays exactly as it does without video. It is an enhancement, never
 * a dependency.
 *
 * Files are generated by `npm run media:assets` from the masters in
 * assets/source/.
 */

export const DOOR_ASSETS = {
  webm: "/brand/doors-open-intro.webm",
  mp4: "/brand/doors-open-intro.mp4",
  poster: "/brand/doors-open-poster.jpg",
} as const;

/** Opacity of the clip before and after the mark takes over. */
const DOOR_OPACITY = { open: 0.9, behindMark: 0.4 } as const;

/**
 * Opacity of the scrim in the same two states. It is never fully off: the door
 * handles and escutcheons land almost exactly where the monogram's waist does,
 * and on a phone they land inside it. A permanent, gentle centre vignette keeps
 * that hardware from reading as part of the mark during the cross-fade, and is
 * invisible while the dust is still spread across the whole frame.
 */
const SCRIM_OPACITY = { open: 0.55, behindMark: 1 } as const;

type ConnectionLike = { saveData?: boolean };

/**
 * True when the visitor has asked their browser to conserve data. A 290 KB
 * decorative video is exactly the sort of thing that request is about.
 */
function prefersLessData(): boolean {
  if (typeof navigator === "undefined") return false;
  const connection = (navigator as Navigator & { connection?: ConnectionLike })
    .connection;
  return connection?.saveData === true;
}

export function IntroDoors({ fadeOut }: { fadeOut: boolean }) {
  const videoRef = useRef<HTMLVideoElement>(null);
  // Starts true so the <video> is never even created for a Data Saver visitor;
  // the effect clears it on the first client tick when the answer is no.
  const [skipped, setSkipped] = useState(true);

  useEffect(() => {
    if (prefersLessData()) return;
    setSkipped(false);
  }, []);

  useEffect(() => {
    const video = videoRef.current;
    if (skipped || !video) return;

    // Autoplay can still be refused (low power mode, an OS-level setting).
    // Treat a rejected play() the same as a missing file.
    const attempt = video.play();
    if (attempt && typeof attempt.catch === "function") {
      attempt.catch(() => setSkipped(true));
    }
  }, [skipped]);

  if (skipped) return null;

  return (
    <>
      <motion.video
        ref={videoRef}
        aria-hidden
        muted
        playsInline
        autoPlay
        preload="auto"
        poster={DOOR_ASSETS.poster}
        onError={() => setSkipped(true)}
        className="pointer-events-none absolute inset-0 h-full w-full object-cover"
        initial={{ opacity: 0 }}
        animate={{
          opacity: fadeOut ? DOOR_OPACITY.behindMark : DOOR_OPACITY.open,
        }}
        transition={{ duration: fadeOut ? 1 : 1.2, ease: [0.22, 1, 0.36, 1] }}
      >
        <source src={DOOR_ASSETS.webm} type="video/webm" />
        <source src={DOOR_ASSETS.mp4} type="video/mp4" />
      </motion.video>

      {/* The scrim. The clip's warm centre is the brightest thing on screen at
          exactly the moment the champagne wordmark appears over it, so this
          deepens the middle back to navy and holds the contrast. Stopping at
          0.74 rather than going solid is deliberate — the room is meant to
          still be glowing behind the mark, not blacked out. */}
      <motion.div
        aria-hidden
        className="pointer-events-none absolute inset-0"
        style={{
          background:
            "radial-gradient(78% 58% at 50% 44%, rgba(1,8,22,0.74) 0%, rgba(1,8,22,0.42) 58%, rgba(1,8,22,0.7) 100%)",
        }}
        initial={{ opacity: SCRIM_OPACITY.open }}
        animate={{
          opacity: fadeOut ? SCRIM_OPACITY.behindMark : SCRIM_OPACITY.open,
        }}
        transition={{ duration: 1, ease: [0.22, 1, 0.36, 1] }}
      />
    </>
  );
}
