/**
 * A photographic backdrop for a section.
 *
 * These images are atmosphere, never evidence. They are rendered dark, low in
 * opacity and under a navy wash so they read as texture behind the type — not
 * as documentation of a room this community has already filled. Nothing on the
 * page captions them, claims them as a past event, or presents them as proof of
 * anything, because none of that would be true yet.
 *
 * Practically:
 *   - `aria-hidden` and empty alt: decorative, so screen readers skip it
 *   - absolutely positioned inside an `overflow-hidden` section: no layout
 *     shift whether it loads in 20ms or never
 *   - lazy and async: never competes with the hero for bandwidth
 *   - WebP first with a JPEG fallback: no runtime image service required, so
 *     this behaves identically on Vercel and on a static export
 *
 * Sources are generated by `npm run media:assets`.
 */

import type { CSSProperties } from "react";

type SectionBackdropProps = {
  /** Path stem under /brand, without extension — e.g. "gathering". */
  src: string;
  /** 0–1. Kept low; these sit behind body copy that has to stay readable. */
  opacity?: number;
  /**
   * 0–1, below the `md` breakpoint. A narrow viewport crops hard into the
   * middle of a landscape image, so the brightest part of it ends up filling
   * the screen behind the copy instead of sitting off to one side. Defaults to
   * `opacity` when the image is calm enough not to need the reduction.
   */
  mobileOpacity?: number;
  /** CSS `object-position`, for choosing what survives the crop. */
  position?: string;
  /**
   * A gradient painted over the image to sink it back into the page. Defaults
   * to a wash that is near-solid navy at the edges and thinnest in the middle.
   */
  scrim?: string;
  className?: string;
};

const DEFAULT_SCRIM =
  "linear-gradient(to bottom, rgb(1 8 22) 0%, rgb(1 8 22 / 0.4) 38%, rgb(1 8 22 / 0.46) 62%, rgb(1 8 22) 100%)";

export function SectionBackdrop({
  src,
  opacity = 0.24,
  mobileOpacity,
  position = "center",
  scrim = DEFAULT_SCRIM,
  className,
}: SectionBackdropProps) {
  return (
    <div
      aria-hidden
      className={`pointer-events-none absolute inset-0 overflow-hidden${
        className ? ` ${className}` : ""
      }`}
    >
      <picture>
        <source srcSet={`/brand/${src}.webp`} type="image/webp" />
        <img
          src={`/brand/${src}.jpg`}
          alt=""
          loading="lazy"
          decoding="async"
          className="h-full w-full object-cover opacity-[var(--backdrop-o)] md:opacity-[var(--backdrop-o-md)]"
          style={
            {
              "--backdrop-o": mobileOpacity ?? opacity,
              "--backdrop-o-md": opacity,
              objectPosition: position,
            } as CSSProperties
          }
        />
      </picture>

      <div className="absolute inset-0" style={{ background: scrim }} />
    </div>
  );
}
